### ISSUE TITLE
Socket-configuration missing (5.7)?

### ISSUE THREAD

**Issue by EugenMayer** [docker-library/percona#25] opened 2016-07-14 11:20 UTC
It seems, like there is no way to connect using a socket ( at least not in 5.7 )

i think we need to do the following during bootstrap

```
mysql -e "INSTALL PLUGIN auth_socket SONAME 'auth_socket.so'"
mysql -e "USE mysql; UPDATE user SET plugin='auth_socket' WHERE user='root'"
```

this enabled socket auth and thus,

```
mysqladmin -h localhost reload
```

works

**Comment by EugenMayer** [comment] 2016-07-14 11:22
Just for the source, this is out of the debian init.d/mysql script and should happen here

https://github.com/docker-library/percona/blob/master/5.7/docker-entrypoint.sh#L47

https://goo.gl/i185pQ

**Comment by EugenMayer** [comment] 2016-07-16 09:25
After fiddling my head around this, i go to things:
- it is interesting to get socket auth running to be able to run `mysqladmin reload` on the server, i case of reconfiguration, but also others

It seems though, that with *mysql/percona 5.7 things changed regarding on the usage of host-wildcards, this said, you cannot use:
`create user root@%` and `create user root@localhost` at the same time. You can do things like  `create user root@a` and `create user root@b` and `create user root@c`
This seems yet to be undocumented and does not really fit what you find about it online, so its either brand new, i could not find the docs or its a bug (but it kinda makes sense)

Still that said, you cannto just add and additional `root@localhost` user, which does has socket_auth as plugin. You also cannot replace the current root@% auth plugin, since this would block any remote connections.

I decided, for now, creating a remote_root@% with mysql_native_password and updating root@% to be root@localhost with socket_auth. I have done this using a additional script in .d

It is kinda "solved" for me, but i thinkg its a more general issue and probably either you should be aware of it or we could try a better solution.

**Comment by tianon** [comment] 2018-05-07 22:52
Sorry for the delay.  I'm unable to reproduce an issue with sockets as described:

```console
$ docker pull percona:5.7
5.7: Pulling from library/percona
Digest: sha256:ec54941f921e03cf33475953a9340f3115051a58f98c55f8c5c03597ae7cd942
Status: Image is up to date for percona:5.7

$ docker run -dit --name test -e MYSQL_ROOT_PASSWORD=test percona
2a5e70bd3f38ac170ccecaca4733719b06af53ea9fbb1a3907a8e9dde8dbaf35

$ docker logs --tail=2 test
2018-05-07T22:50:52.740076Z 0 [Note] mysqld: ready for connections.
Version: '5.7.21-20'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Percona Server (GPL), Release '20', Revision 'ed217b06ca3'

$ docker exec -it test bash
root@2a5e70bd3f38:/# mysqladmin -h localhost -uroot -ptest reload
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
root@2a5e70bd3f38:/# exit

$ docker logs --tail=10 test
2018-05-07T22:50:52.739932Z 0 [Note] Event Scheduler: Loaded 0 events
2018-05-07T22:50:52.740076Z 0 [Note] mysqld: ready for connections.
Version: '5.7.21-20'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Percona Server (GPL), Release '20', Revision 'ed217b06ca3'
2018-05-07T22:51:23.300273Z 2 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2018-05-07T22:51:23.300311Z 2 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-05-07T22:51:23.300325Z 2 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-05-07T22:51:23.300329Z 2 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-05-07T22:51:23.300337Z 2 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2018-05-07T22:51:23.300482Z 2 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-05-07T22:51:23.300489Z 2 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
```

Closing, since this doesn't appear to be an issue in the image itself.

**Closed as completed by tianon** 2018-05-07 22:52 UTC
Labels: Issue
